server:
  port: 30150

spring:
  profiles:
    active: dev
  #   active: uat
  #    active: prod
  application:
    name: yhdx-scm-shards
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-init-sqls: SET NAMES utf8mb4

mybatis:
  mapperLocations: classpath*:*Mapper.xml


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  scm-shards-service:
    name: ${spring.application.name}


eureka:
  instance:
    perfer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    hostname: ${spring.cloud.client.ip-address}
    metadata-map:
      group: yhdx-scm-shards-group
      address: ${spring.cloud.client.ip-address}:${com.alipay.sofa.lookout.prometheus-exporter-server-port}
  client:
    registry-fetch-interval-seconds: 5
  server:
    enable-self-preservation: false


myconf:
  applicationId: 150
  namespace: scm2
  sharding:
    sync:
      exchangeName: yhdx.scm.exchanger.shards.sync
      queueName: yhdx.scm.q.shards.sync


# springboot2 actuator配置(只开启info,health,restart,pause)
# 由于pause是restart的子类，需开启restart后才可以开启pause
management:
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
  endpoint:
    restart:
      enabled: true
    pause:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
        # include: ["info","health","shutdown","restart","pause"]

#  sofa端口
com:
  alipay:
    sofa:
      lookout:
        prometheus-exporter-server-port: 30151